repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: flake8
    args: ["--ignore=F405,E731,F403,W503,E722,E203", --max-line-length=120]
    # F405 : Name may be undefined, or defined from star imports: module
    # E731 : Do not assign a lambda expression, use a def
    # F403 : 'from module import *' used; unable to detect undefined names
    # W503 : Line break before binary operator
    # E722 : Do not use bare 'except'
    # E203 : Whitespace before ':'

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/psf/black.git
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.11
    - id: black-jupyter
