
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: flag-gems-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  container-test-job:
    runs-on: [self-hosted, docker]
    container:
      image: localhost:5000/flag-gems-ci:v1.0
      ports:
        - 80
      options: --gpus all --hostname flag-gems_cicd
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: unit_test-flag-gems
        run: |
          pytest -s tests/test_*

      - name: examples-flag-gems
        run: |
          pytest -s examples/model_*
