
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: flag-gems-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  container-unit-test:
    runs-on: [self-hosted, docker]
    container:
      image: localhost:5000/flag-gems-ci:v1.0
      ports:
        - 81
      options: --gpus all --hostname flag-gems_cicd_ut
    strategy:
      max-parallel: 5
      matrix:
        device: [0, 1, 2, 3, 4]
        include: 
          - file: test_unary_pointwise_ops.py
            device : 0
          - file: test_binary_pointwise_ops.py
            device : 1
          - file: test_blas_ops.py
            device : 2
          - file: test_reduction_ops.py
            device : 3
          - file: test_special_ops.py
            device : 4
    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: unit_test-flag-gems
        run: |
          CUDA_VISIBLE_DEVICES= ${{ matrix.device }} pytest -s tests/${{ matrix.file }}
  
  container-model-test:
    runs-on: [self-hosted, docker]
    container:
      image: localhost:5000/flag-gems-ci:v1.0
      ports:
        - 82
      options: --gpus all --hostname flag-gems_cicd_model -v /home/flaggems_cicd/huggingface_cache_bert:/__w/_temp/_github_home/.cache/huggingface
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: examples-flag-gems
        run: |
          CUDA_VISIBLE_DEVICES=5 pytest -s examples/model_bert_test.py
